*error_aggregateTwoErrors.js:*
throw aggregateTwoErrors(err, originalError);
^
[AggregateError: original] {
  code: 'ERR0',
  [errors]: [
    Error: original
        at Object.<anonymous> (*test*message*error_aggregateTwoErrors.js:*:*) {
      code: 'ERR0'
    },
    Error: second error
        at Object.<anonymous> (*test*message*error_aggregateTwoErrors.js:*:*) {
      code: 'ERR1'
    }
  ]
}

Node.js *
